dist: xenial

language: python

sudo: false

python:
  - 3.7
  - 3.6

install:
  - pip install coverage coveralls

script:
  - coverage run --source=ctyped setup.py test

after_success:
  - coveralls
